name: CI
on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: '${{ secrets.DB_HOST }}'
      DB_USER: '${{ secrets.DB_USER }}'
      DB_PASSWORD: '${{ secrets.DB_PASSWORD }}'
      DB_MYSQL: '${{ secrets.DB_MYSQL }}'
      DB_DIALECT: '${{ secrets.DB_DIALECT }}'
      APP_PORT: '${{ secrets.APP_PORT }}'
      DB_PORT: '${{ secrets.DB_PORT }}'

    strategy:
      matrix:
        node-version:
          - 18.x

    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - name: 'Using, Node, Express, and Sequelize'
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: npm
      - run: sudo systemctl start mysql
      - run: systemctl status mysql
      - run: sudo apt-get install -y wait-for-it
      - run: wait-for-it --timeout=60 ${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }} -s -- echo "MySQL is up"
      - run: sudo mysql --user=${{ secrets.DB_USER }} --password=${{ secrets.DB_PASSWORD }} -e "create database ${{ secrets.DB_MYSQL }}";
      - run: npm test