name: Integ-Testing

on:
  pull_request:
    branches:
      - main

jobs:
  integration:
      runs-on: ubuntu-latest

      services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
            POSTGRES_DATABASE: webapp
          ports:
            - 3306:3306
          

      env:
        DB_HOST: localhost
        DB_PORT: 3306
        DB_USER: root
        DB_DIALECT: postgres
        DB_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
        DB_NAME: webapp
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "14"

        - name: Install Dependencies
          run: npm install

        - name: Setup Packer
          uses: hashicorp/setup-packer@main
          id: setup
          with:
            version: "latest"

        - name: Create Zip Artifact
          run: |
            zip -r repository.zip .

        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: repository
            path: repository.zip . -x "*.git*"

        - name: Create .env file
          run: |
            echo DB_HOST=127.0.0.1 >> .env
            echo DB_USER=root >> .env
            echo DB_DIALECT=postgres >> .env
            echo DB_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} >> .env
            echo DB_NAME=postgres >> .env
            echo TEST_DB_NAME=assignment_portal >> .env

        - name: Packer init
          run: |
            packer init packer/debian.pkr.hcl

        - name: Validate Packer Config
          run: |
            cd packer
            packer fmt --check debian.pkr.hcl
            packer validate -var "db_root_password=${DB_ROOT_PASSWORD}" debian.pkr.hcl
