name: Buid packer Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-packer:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo DB_HOST=127.0.0.1 >> .env
          echo DB_USER=root >> .env
          echo DB_DIALECT=postgres >> .env
          echo DB_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} >> .env
          echo DB_NAME=postgres >> .env
          echo TEST_DB_NAME=assignment_portal >> .env

      - name: Create Zip Artifact
        run: |
          zip -r repository.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: repository
          path: repository.zip . -x "*.git*"

      - name: Packer init
        run: |
          packer init packer/aws-ubuntu.pkr.hcl

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Build Packer Image
        run: |
          cd packer
          packer build -var "db_root_password=${DB_ROOT_PASSWORD}" aws-ubuntu.pkr.hcl
