name: Push to Main Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  packer_ci:
    build-and-deploy:
      runs-on: ubuntu-latest

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Create .env file
          run: |
            echo DB_HOST=127.0.0.1 >> .env
            echo DB_USER=root >> .env
            echo DB_DIALECT=mysql >> .env
            echo DB_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} >> .env
            echo DB_NAME=mysql >> .env
            echo TEST_DB_NAME=assignment_portal >> .env

        - name: Create Zip Artifact
          run: |
            zip -r repository.zip .

        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: repository
            path: repository.zip . -x "*.git*"

        - name: Packer init
          run: |
            packer init packer/aws-ubuntu.pkr.hcl

        - name: Run packer fmt
          run: packer fmt -check -recursive .

        - name: Run packer validate
          run: packer validate .

