name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  validate-packer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # You can specify the desired version

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Zip all files
        run: zip -r webapp.zip .

      - name: Create .env file
          run: |
            echo DB_HOST=127.0.0.1 >> .env
            echo DB_USER=root >> .env
            echo DB_DIALECT=postgres >> .env
            echo DB_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} >> .env
            echo DB_NAME=postgres >> .env
            echo TEST_DB_NAME=assignment_portal >> .env

      - name: Run `packer init`
        id: init
        run: packer init .

      - name: Run packer fmt
        run: packer fmt -check -recursive .

      - name: Run packer validate
        run: packer validate .