name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  validate-packer:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # You can specify the desired version

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Zip all files
        run: zip -r webapp.zip .

      - name: Run `packer init`
        id: init
        run: packer init .

      - name: Run packer fmt
        run: packer fmt --check aws-debian.pkr.hcl

      - name: Fail if packer fmt fails
        if: ${{ steps.setup.outputs.exit-code != 0 }}
        run: exit 1

      - name: Run packer validate
        run: packer validate .

      - name: Fail if packer validate fails
        if: ${{ steps.setup.outputs.exit-code != 0 }}
        run: exit 1
