name: Packer CI

on:
  pull_request:
    paths:
      - '../../packer/aws-ubuntu.pkr.hcl'
      - '../../packer/install.sh'

jobs:
  packer-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.7/packer_1.7.7_linux_amd64.zip
          unzip packer_1.7.7_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Run packer fmt
        run: packer fmt -check -recursive .

      - name: Run packer validate
        run: packer validate .

