name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v1

      - name: Build and Share AMI
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEV_ACCOUNT_ID: ${{ secrets.DEV_ACCOUNT_ID }}
          DEMO_ACCOUNT_ID: ${{ secrets.DEMO_ACCOUNT_ID }}
        run: |
          packer build -var 'source_ami=ami-xxxxxxxxxxxxxxxxx' \
                       -var 'region=${AWS_REGION}' \
                       -var 'dev_account_id=${DEV_ACCOUNT_ID}' \
                       -var 'demo_account_id=${DEMO_ACCOUNT_ID}' \
                       packer/aws-ubuntu.pkr.hcl

